DATA_TYPE: "data type"
HEMISPHERE: "hemisphere"
IS_SPECIFIC: "is specific"
PROCESS_METHOD: "process method"
REGION: "region"
SIMILARITY: "similarity"
SIMILARITY_METHOD: "similarity method"
STRUCTURE: "structure"
STIMULATION: "stimulation"
SUBJECT: "subject"
SUBJECT_ID: "subject ID"
SUBSET_TYPE: "subset type"
IMAGES: "images"

