# You can change the formats as you need, but not the variable names.
datatype_stimulation_label: "f\"{stimulation} ({data_type})\""
process_similarity_field: "f\"{similarity_name} ({process_name})\""
region_label: "f\"{structure} {hemisphere}\""